# IMPORTANT: For production environemnts, specify the image from releases directory with an explicit version tag.
# e.g. dataspark-docker-releases.artifactory.datasparkanalytics.com/dataspark/capex-service:1.14.0'
version: '3'
services:
  zookeeper:
    image: 'bitnami/zookeeper:3.4.14-debian-9-r24'
    restart: unless-stopped
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:2.2.0-debian-9-r37'
    restart: unless-stopped
    ports:
      - '9092:9092'
      - '29092:29092'
    volumes:
      - ./data/kafka:/bitnami/kafka
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      #Adding listener for internal and external clients - https://rmoff.net/2018/08/02/kafka-listeners-explained/